version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-p1 --output-template-file seach.yaml
artifacts:  
  type: zip
  files:
    - search.yaml