AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_photo_search.lambda_handler
      Runtime: python3.7
      CodeUri: s3://codepipeline-p1/fe06a88946d09f65ab17427496cb8ce3
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::554887605142:role/service-role/photossearch-role-8fwglxt2
